version: "3.5"

services:
  api01: &api
    image: ghcr.io/lpicanco/backend-dogfight-rust-24-q1:v2
    hostname: api01
    network_mode: host
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://dogfight_user:dogfight_pass@db:5432/dogfight
      PORT: 3042
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: "50MB"

  api02:
    <<: *api
    hostname: api02
    environment:
      DATABASE_URL: postgres://dogfight_user:dogfight_pass@db:5432/dogfight
      PORT: 3043
  nginx:
    image: nginx:1.25.3
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    network_mode: host
    depends_on:
      - api01
      - api02
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "50MB"

  db:
    image: postgres:16.1
    hostname: db
    restart: unless-stopped
    network_mode: host
    environment:
      POSTGRES_DB: dogfight
      POSTGRES_USER: dogfight_user
      POSTGRES_PASSWORD: dogfight_pass
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c synchronous_commit=off -c max_connections=300 -c max_wal_size=4096 -c checkpoint_timeout=600
    deploy:
      resources:
        limits:
          cpus: '1.10'
          memory: "400MB"
