version: '3.9'

services:
  api1: &api
    image: lucassperez/go-crebito:latest
    build:
      dockerfile: Dockerfile
      target: prod
    hostname: api1
    environment:
      SERVER_ADDRESS: 4000
      DB_HOST: db
      DB_USER: rinheiro
      DB_PASSWORD: rinha123
      DB_NAME: rinha-go-crebito
    volumes:
      - .:/app
    ports:
      - 4000:4000
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '55MB'

  api2:
    <<: *api
    hostname: api2
    ports:
      - 4001:4000

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: rinheiro
      POSTGRES_PASSWORD: rinha123
      POSTGRES_DB: rinha-go-crebito
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./seed.sql:/docker-entrypoint-initdb.d/2-seed.sql
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          cpus: '1.2'
          memory: '400MB'

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - 9999:9999
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '40MB'
