version: "3.5"

services:
  api1: &api
    image: thicsilva/rb2024q1:latest
    hostname: api1
    depends_on:
      - db
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "125MB"
    ports:
      - 8081:8080

  api2:
    <<: *api
    hostname: api2 
    ports:
      - 8082:8080
  
  nginx:
    image: nginx:latest
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "20MB"
    ports:
      - 9999:9999

  db:    
    image: mariadb:latest
    hostname: db
    environment:
      - MARIADB_ROOT_PASSWORD=rootPass
      - MARIADB_USER=root
      - MARIADB_DB=rinha    
      - TZ=UTC  
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    volumes:
      - ./init/script.sql:/docker-entrypoint-initdb.d/script.sql
      - ./config/mariadb/perf.cnf:/etc/mysql/conf.d/perf.cnf -r
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "280MB"
    ports:
      - 3307:3306

networks:
  default:
    driver: bridge
    name: rinha
    driver_opts:
      com.docker.network.driver.mtu: 9000
