version: '3.5'
services:
  api1: &api
    # API - Inst√¢ncia 01
    image: engylemure/rinha-de-backend-2024-q1:latest
    hostname: api01
    depends_on:
      - db
    env_file: ./env
    environment:
      - RUST_ENV=prod
      - RUST_LOG=info
      - TARGET_NAME=rinha
      - DATABASE_POOL_MAX_SIZE=224
      - DATABASE_POOL_MIN_SIZE=32
      - SERVER_PORT=80
      - SERVER_HOST=0.0.0.0
      # - LOGGER_OUTPUT=stdout
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '32MB'
  api2:
    # API - Instancia 02
    <<: *api
    hostname: api02
  nginx:
    # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '128MB'
  db:
    # Banco de dados
    image: postgres:16.1
    hostname: db
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: rinha_de_backend
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    command: postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.conf
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '358MB'
networks:
  default:
    driver: bridge
