version: '3.5'

services:
  api01: &api
    image: felipefrmelo/rinha_de_backend_2024_q1:v1
    hostname: api01
    ports:
      - '3001:3000'
    depends_on:
      db:
        condition: service_healthy

    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: '100MB'

  api02:
    <<: *api
    hostname: api02
    ports:
      - '3002:3000'

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - '9999:9999'
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '10MB'

  db:
    image: postgres:latest
    hostname: db
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'admin', '-d', 'rinha']
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - '5432:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096 -c synchronous_commit=0 -c full_page_writes=0
    deploy:
      resources:
        limits:
          cpus: '0.65'
          memory: '340MB'
