version: "3.5"

networks:
  rinha-network:

services:
  api01:
    image: hfurlan/rinha-backend-2024-q1:1.1.0-go
    #image: rinha-backend-2024-q1-go
    hostname: api01
    environment:
      - DB_HOSTNAME=db
      - DB_USER=admin
      - DB_PASSWORD=123
      - DB_NAME=rinha
      - DB_MAX_CONNECTIONS=10
      - HTTP_PORT=8081
      # - PING_TRANSACOES_INSERT_ONLY_ON=true
    ports:
      - "8081:8081"
    depends_on:
      - db
    restart: on-failure
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"

  api02:
    image: hfurlan/rinha-backend-2024-q1:1.1.0-go
    #image: rinha-backend-2024-q1-go
    hostname: api02
    environment:
      - DB_HOSTNAME=db
      - DB_USER=admin
      - DB_PASSWORD=123
      - DB_NAME=rinha
      - DB_MAX_CONNECTIONS=10
      - HTTP_PORT=8082
      # - PING_TRANSACOES_INSERT_ONLY_ON=true
    ports:
      - "8082:8082"
    depends_on:
      - db
    restart: on-failure
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"
 
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
        # Obrigatório expor/usar a porta 9999 no load balancer!
      - "9999:9999" 
    restart: on-failure
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "10MB"

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    networks:
      - rinha-network
    volumes:
      - ./sql/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
      - ./sql/dml.sql:/docker-entrypoint-initdb.d/dml.sql
    command: postgres -c 'max_connections=22'
    deploy:
      resources:
        limits:
          # Note que a soma de todos os limites dos serviços
          # aqui declarados é de 1.5 unidades de CPU e 550MB
          # de memória. A distribuição feita aqui é apenas
          # um exemplo – distribua como quiser.
          cpus: "0.8"
          memory: "350MB"

# O uso do modo `bridge` deve ser adequado à carga que será usada no teste.
# A edição anterior se beneficiou do modo host pois o volume de requisições
# era relativamente alto e a virtualização da rede se tornou um gargalo, mas
# este modo é mais complexo de ser configurado. Fique à vontade para usar o
# modo que quiser desde que não conflite com portas trivialmente usadas em um
# SO.
# networks:
#   default:
#     driver: bridge
#     name: rinha-nginx-2024q1
