services:
  api1: &api
    image: thiagotn/rinhafastapi:1.0
    hostname: api1
    command: uvicorn app.main:app --port 3000
    network_mode: host
    environment:
      - MAX_CONNECTIONS=10
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "95MB"

  api2: 
    <<: *api
    hostname: api2
    command: uvicorn app.main:app --port 3001

  db:
    image: postgres:16
    hostname: db
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf
      - type: tmpfs
        target: /var/lib/postgresql/data
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    network_mode: host
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rinha -d rinha -h localhost -p 5432"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: rinha
      POSTGRES_DB: rinha
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "330MB"

  nginx:
    image: nginx 
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    network_mode: host
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30MB"