version: "3.5"

services:
  api01: &api
    image: lucianovilela/rinha-backend-2024-q1-fastify:latest
    hostname: api01
    environment:
      - USERDB=admin
      - HOSTDB=localhost
      - DB=rinha
      - PASSWORDDB=123
      - PORTS=9000,9001
#      - UV_THREADPOOL_SIZE=5
      - MAX=10
    network_mode: host
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "150MB"

  api02:
    <<: *api
    hostname: api02
    environment:
      - USERDB=admin
      - HOSTDB=localhost
      - DB=rinha
      - PASSWORDDB=123
      - PORTS=9003,9004
#      - UV_THREADPOOL_SIZE=5
      - MAX=10

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "100MB"

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    network_mode: host
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'  
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "150MB"

