version: "3.5"

services:
  app1: &app
    # container_name: api1
    image: normanfrieman/clicbank:latest
    hostname: api1
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Port=5432;Database=clicbank;Pooling=true;Minimum Pool Size=50;Maximum Pool Size=75;Username=postgres;Password=1234
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "8081:8080"
    # network_mode: host
    depends_on:
      - db
      # db:
      #   condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '155MB'
  
  app2:
    <<: *app
    # container_name: api2
    hostname: api2
    ports:
      - "8082:8080"
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    ports:
      - "9999:9999"
    # network_mode: host
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '10MB'
  
  db:
    image: postgres:16.2
    hostname: db
    command: 'postgres -c max_connections=150'
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=clicbank
    ports:
      - "5432:5432"
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    # network_mode: host
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '230MB'

networks:
  default:
    driver: bridge
    name: the-final-improvise