version: "3.8"

services:
  api01: &api
    image: whyakari/rinha:2.0
    hostname: api01
    environment:
      - DB_HOSTNAME=db
      - DB_USER=root
      - DB_PASSWORD=love
      - DB_NAME=rinha
      - DB_PORT=3306
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "100MB"

  api02:
    <<: *api
    hostname: api02
    environment:
      - DB_HOSTNAME=db
      - DB_USER=root
      - DB_PASSWORD=love
      - DB_NAME=rinha
      - DB_PORT=3306

  shinsei:
    image: whyakari/shinsei:latest
    depends_on:
      - api01
      - api02
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "20MB"

  db:
    image: mariadb:latest
    restart: always
    container_name: db
    hostname: db
    environment:
      - MYSQL_ROOT_PASSWORD=love 
      - MYSQL_DATABASE=rinha 
      - MYSQL_PASSWORD=love
    ports:
      - "3306:3306"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized"
        ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: "0.95"
          memory: "310MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1

