services:
  api01: &api
    image: cassiogangrel/deno_rinha_e2:1.0.0
    hostname: api01
    depends_on:
      - postgres
    restart: on-failure
    environment: 
      - PORT=8080
      - DB_HOST=postgres
      - DB_POOL_SIZE=30
    healthcheck:
      test:
        - CMD-SHELL
        - wget --quiet --tries=1 --spider http://localhost:9999/healthcheck ||
          exit 1
      interval: 15s
      timeout: 15s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "120MB"
  api02:
    <<: *api
    depends_on:
      - api01
      - postgres

  postgres:
    image: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/script.sql
    environment:
      - POSTGRES_DB=rinha
      - POSTGRES_USER=rinha
      - POSTGRES_PASSWORD=rinha
    deploy:
      resources:
        limits:
          cpus: "0.70"
          memory: "300MB"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: on-failure
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "10MB"

networks:
  default:
    driver: bridge
    name: rinha