version: "3.5"
services:

  api01: &api
    image: wladimirteixeiraneto/rinha-mongo:latest
    hostname: api01
    environment:
      - PORT=5001
      - DB_HOST=mongodb
      - DB_USER=username
      - DB_PASSWORD=password
      - DB_NAME=rinha
      - DB_PORT=27017
    networks:
      - crebito-network
    depends_on:
      mongodb:
        condition: service_healthy
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "165MB"
  
  api02:
    <<: *api
    hostname: api02
    environment:
      - PORT=5002
      - DB_HOST=mongodb
      - DB_USER=username
      - DB_PASSWORD=password
      - DB_NAME=rinha
      - DB_PORT=27017

  mongodb:
    #image: mongo
    image: mongo:latest
    restart: always
    command: mongod --quiet --logpath /dev/null
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017:27017"
    expose:
      - "27017"
    networks:
      - crebito-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 15s
      retries: 5
      start_period: 15s
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "200MB"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    networks:
      - crebito-network
    depends_on:
      - api01
      - api02
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "20MB"

networks:
  crebito-network:
    driver: bridge