version: '3'

services:
  rinha-api-01: &api
    image: edmarsousa/rinha-api:latest
    
    hostname: rinha-api-01  
    container_name: rinha-api-01

    ports:
      - "8001:9501"

    environment:
      HTTP_PORT: 9501
      APP_NAME: rinha_backend_2024
      APP_ENV: dev

      DB_DRIVER: pgsql
      DB_HOST: db
      DB_PORT: 5432

      DB_DATABASE: rinhadb
      DB_USERNAME: postgre
      DB_PASSWORD: postgre

    depends_on:
      - db

    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "160MB"

  rinha-api-02:
    <<: *api
    hostname: rinha-api-02
    container_name: rinha-api-02

    ports:
      - "8002:9501"

    depends_on:
      - db

  db:
    container_name: rinha-backend-db
    image: postgres:15.4

    environment:
      POSTGRES_DB: rinhadb
      POSTGRES_PASSWORD: postgre
      POSTGRES_USER: postgre

    command: postgres -c config_file=/etc/postgresql/postgresql.conf

    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres.conf:/etc/postgresql/postgresql.conf

    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "210MB"

  nginx:
    image: nginx:latest
    container_name: nginx-rinha-2024

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

    depends_on:
      - rinha-api-01
      - rinha-api-02

    ports:
      - "9999:9999"
    
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "20MB"

networks:
  default:
    driver: bridge
    name: rinha-backend-2024
