version: "3.5"

services:
  api_csharp:
    image: gldmelo/rinhabackendcrebito:1.5-aot
    hostname: api_csharp
    environment:
      - ASPNETCORE_URLS=http://*:8080
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "60MB"

  api_python:
    image: gldmelo/rinhabackendcrebito:1.0-py
    hostname: api_python
    command: uvicorn src.main:app --proxy-headers --host 0.0.0.0 --port 8000
    ports:
      - 8001:8000
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "60MB"
      
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api_csharp
      - api_python
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "90MB"
    
  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: [ "postgres", "-c", "config_file=/etc/postgresql/postgresql.conf" ]
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "admin" ]
      timeout: 40s
      interval: 2s
      retries: 20
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: "340MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
    driver_opts:
      com.docker.network.driver.mtu: 1024
