version: '3.8'

services:
  api1: &api
    image: diegocoronel/diego-coronel:rinha-backend-01-2024-T4
    container_name: api1
    environment:
      - quarkus.datasource.jdbc.url=jdbc:postgresql://postgres:5432/rinha-de-backend-2024
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: '100MB'

  api2:
    <<: *api
    container_name: api2

  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_DB=rinha-de-backend-2024
      - POSTGRES_USER=rinha
      - POSTGRES_PASSWORD=backend
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: '320MB'

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 9999:9999
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '30MB'
