version: "3.5"
services:
  api01: &api
    image:  felipecassiano/manuelzinho-rinha:latest
    hostname: api01
    restart: unless-stopped
    networks:
      - default
    environment:
      - APP_PORT=3000
      - DATABASE_URL=postgres://rinha:rinha@db:5432/rinha?sslmode=disable
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "100MB"

  api02:
    <<: *api
    hostname: api02

  db:
    image: postgres:latest
    hostname: db
    restart: unless-stopped
    networks:
      - default
    environment:
      POSTGRES_DB: rinha
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: rinha
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    command: postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.conf 
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: "300MB"

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      -  ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    depends_on:
      - api01
      - api02
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '50MB'

networks:
  default:
    driver: bridge
    name: rinha-network
