version: "3.8"

services:
  drogon_pg_database:
    container_name: drogon_pg_database
    image: postgres:16.1-alpine3.19
    volumes:
      - ./configure.sql:/docker-entrypoint-initdb.d/configure.sql
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "log_statement=all"]
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "300MB"

  drogon_api_1:
    container_name: drogon_api_1
    image: lipeferreira1609/dev_bank_with_drogon_framework:latest
    depends_on:
      - drogon_pg_database
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "120MB"

  drogon_api_2:
    container_name: drogon_api_2
    image: lipeferreira1609/dev_bank_with_drogon_framework:latest
    depends_on:
      - drogon_pg_database
      - drogon_api_1
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "120MB"

  drogon_nginx:
    container_name: drogon_nginx
    image: nginx:latest
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - drogon_api_1
      - drogon_api_2
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "10MB"

networks:
  default:
    driver: bridge
    name: rinha-backend-2024
