volumes:
  db-data:
networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
services:
  loadbalancer:
    image: nginx:latest
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend1
      - backend2
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"
  db:
    image: ghcr.io/lucasew/playground-rinha202401-tigerbeetle:latest
    # build:
    #   dockerfile: ./Dockerfile.tigerbeetle-lowram
    entrypoint: /tigerbeetle-start.sh
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "400MB"
    # deploy:
      # resources:
      #   limits:
      #     memory: 1024M
    volumes:
    - db-data:/data
    - ./tigerbeetle-start.sh:/tigerbeetle-start.sh
  backend1:
    image: ghcr.io/lucasew/playground-rinha202401-backend:latest
    restart: always
    environment:
      - "TB_ADDRESS=db:3000"
      - "TIGERBEETLE_MAX_CONCURRENCY=320"
      - "GOMEMLIMIT=45MiB"
      - "GOGC=1000"

    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "50MB"
    # build:
    #   dockerfile: ./Dockerfile.go-backend
    depends_on:
      - db

  backend2:
    image: ghcr.io/lucasew/playground-rinha202401-backend:latest
    restart: always
    environment:
      - "TB_ADDRESS=db:3000"
      - "TIGERBEETLE_MAX_CONCURRENCY=320"
      - "GOMEMLIMIT=45MiB"
      - "GOGC=1000"

    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "50MB"
    # build:
    #   dockerfile: ./Dockerfile.go-backend
    depends_on:
      - db
