version: "3.5"

services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: your_email@example.com
      PGADMIN_DEFAULT_PASSWORD: your_password
    ports:
      - "5050:80"
      
  netcore01: &api
    image: fabriciocoimbra/rinhabackend2024:latest
    hostname: netcore01
    environment:
      - ConnectionStrings__DefaultConnection = "Não funcionou"
      - PORT=8080
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "120MB"

  netcore02:
    <<: *api
    hostname: netcore02
    environment:
      - ConnectionStrings__DefaultConnection = "Não funcionou"
      - PORT=8080
    ports:
      - "8080:8080"
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - netcore01
      - netcore02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "40MB"

  postgres:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=makeLifeSimple
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinhadb
    ports:
      - "5432:5432"
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "270MB"

networks:
  default:
    driver: bridge
    name: garnize
