version: "3.5"

services:
  api01: &api
    image: alcideslins/rinha-app-quarkus:latest
    hostname: api01
    environment:
      - DB_HOSTNAME=db
      - DB_POOL_SIZE=10
      - WARMUP_ENABLED=true
      - WARMUP_HOST=http://api01:8080
      - WARMUP_DELAY_SECONDS=3
      - WARMUP_REQUESTS=10
    ports:
      - "8081:8080"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "220MB"

  api02:
    <<: *api
    hostname: api02
    environment:
      - DB_HOSTNAME=db
      - DB_POOL_SIZE=10
      - WARMUP_ENABLED=true
      - WARMUP_HOST=http://api02:8080
      - WARMUP_DELAY_SECONDS=3
      - WARMUP_REQUESTS=10
    ports:
      - "8082:8080"

  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "15MB"

  db:
    image: postgres:latest
    command: 'postgres -c max_connections=22 -c shared_buffers=16MB -c checkpoint_timeout=600 -c synchronous_commit=off -c fsync=off -c full_page_writes=off -c work_mem=4MB'
    hostname: db
    environment:
      - POSTGRES_DB=rinhadb
      - POSTGRES_USER=rinha
      - POSTGRES_PASSWORD=rinha123
    ports:
      - "5432:5432"
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "95MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1