version: '3.5'

services:
  api01: &api
    image: felipefrmelo/rinha_de_backend_2024_q1:uvicorn
    hostname: api01
    network_mode: host
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
      - POSTGRES_HOST=localhost
      - POSTGRES_MAX_CONNECTIONS=4
      - POSTGRES_MIN_CONNECTIONS=1
      - PORT=3001

    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: '100MB'

  api02:
    <<: *api
    hostname: api02
    environment:
      - PORT=3002

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '10MB'

  db:
    image: postgres:latest
    hostname: db
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'admin', '-d', 'rinha']
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    network_mode: host
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4GB -c synchronous_commit=off -c full_page_writes=off -c max_connections=100
    deploy:
      resources:
        limits:
          cpus: '0.65'
          memory: '340MB'
