version: "3.9"
name: 'rinha-gabrielmagalhaes'

services:
  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    command: ["postgres", "-c", "logging_collector=false", "-c", "max_connections=30"]
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: '320MB'
    healthcheck:
      test: ["CMD-SHELL", "psql -h localhost -U admin -d rinha -c 'SELECT 1;'"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    networks:
      - rinha

  api01: &api
    image: k4gero/quarkus-rinha-back-2024-q1:latest
    hostname: api01
    environment:
      - PORT=8081
      - MAX_CONNECTIONS=15
      - DB_URL=postgresql://db:5432/rinha
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: '80MB'
    networks:
      - rinha

  api02: 
    <<: *api
    hostname: api02
    depends_on:
      - db
      - api01
    environment:
      - PORT=8082
      - MAX_CONNECTIONS=15
      - DB_URL=postgresql://db:5432/rinha
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
    ports:
      - "8082:8080"
    networks:
      - rinha
     
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999" 
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "70MB"
    networks:
      - rinha

networks:
  rinha:
    driver: bridge