version: "3.0"
name: 'rinha-gustavofbreunig'

services:
  api01:
    hostname: api01
    image: gustavofbreunig/ddd-rinha-2023-q1:latest
    environment:
      - DB_HOSTNAME=db
        #    ports:
        #      - "8081:8080"      
    deploy:
      resources:
        limits:
          cpus: "0.525"
          memory: "160MB"

  api02:
    hostname: api02
    image: gustavofbreunig/ddd-rinha-2023-q1:latest
    environment:
      - DB_HOSTNAME=db
        #    ports:
        #      - "8082:8080"        
    deploy:
      resources:
        limits:
          cpus: "0.525"
          memory: "160MB"

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "9999:9999"
    depends_on:
      - api01
      - api02
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "30MB" 

  db:
    hostname: db
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=clientes
    ports:
      - "5432:5432"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: 'postgres -c max_connections=300 -c shared_buffers=96MB -c checkpoint_timeout=600 -c synchronous_commit=off -c fsync=off -c full_page_writes=off -c work_mem=16MB'
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "200MB"
    healthcheck:
      test: ["CMD", "pg_isready", "--username=admin", "--dbname=clientes"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 15s
      start_interval: 1s

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
